(function(){"use strict";const THRESHOLD=0.72;const TIMEOUT_MS=900;async function sha256Hex(str){const data=new TextEncoder().encode(str);const hashBuffer=await crypto.subtle.digest("SHA-256",data);const bytes=new Uint8Array(hashBuffer);return Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("")}
function getWebGLRenderer(){try{const canvas=document.createElement("canvas");const gl=canvas.getContext("webgl")||canvas.getContext("experimental-webgl");if(!gl)return"";const debugInfo=gl.getExtension("WEBGL_debug_renderer_info");if(!debugInfo)return"";const renderer=gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL)||"";return String(renderer).toLowerCase()}catch(e){return""}}
async function getCanvasFingerprint(){try{const canvas=document.createElement("canvas");canvas.width=280;canvas.height=60;const ctx=canvas.getContext("2d");ctx.textBaseline="top";ctx.font="14px 'Arial'";ctx.fillStyle="#f60";ctx.fillRect(0,0,280,60);ctx.fillStyle="#069";ctx.fillText("android-check - 𝒜",8,8);ctx.fillStyle="rgba(102, 200, 0, 0.7)";ctx.fillText("⟂",200,20);ctx.beginPath();ctx.arc(50,40,6,0,Math.PI*2);ctx.fill();const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let s="";for(let i=0;i<data.length;i+=10)s+=data[i]+",";return await sha256Hex(s)}catch(e){return""}}
async function getAudioFingerprint(){try{const sampleRate=44100;const length=2048;const ctxClass=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!ctxClass)return"";const ctx=new ctxClass(1,length,sampleRate);const o=ctx.createOscillator();const compressor=ctx.createDynamicsCompressor();o.type="sine";o.frequency.value=440;o.connect(compressor);compressor.connect(ctx.destination);o.start(0);const buffer=await ctx.startRendering();const channelData=buffer.getChannelData(0);let s="";for(let i=0;i<channelData.length;i+=64)s+=Math.floor(channelData[i]*1e6)+",";return await sha256Hex(s)}catch(e){return""}}
function captureMotion(timeout=600){return new Promise((resolve)=>{let seen=!1;function handler(ev){if(!ev)return;const a=ev.accelerationIncludingGravity||ev.acceleration||null;if(a&&(a.x||a.y||a.z))seen=!0}
try{window.addEventListener("devicemotion",handler,{passive:!0})}catch(e){}
setTimeout(()=>{try{window.removeEventListener("devicemotion",handler)}catch(e){}
resolve(seen)},timeout)})}
async function getBatteryInfo(){try{if(!navigator.getBattery)return null;const batt=await navigator.getBattery();return{level:batt.level,charging:!!batt.charging}}catch(e){return null}}
function androidBaseSignals(){const ua=(navigator.userAgent||"").toLowerCase();const platform=(navigator.platform||"").toLowerCase();const vendor=(navigator.vendor||"").toLowerCase();const uaAndroid=ua.includes("android");const platformAndroid=platform.includes("android");const vendorAndroid=vendor.includes("google")||vendor.includes("android");return{uaAndroid,platformAndroid,vendorAndroid,ua,platform,vendor}}
function uiCapabilities(){const touch=(navigator.maxTouchPoints&&navigator.maxTouchPoints>0)||('ontouchstart' in window);const hasOrientation="onorientationchange" in window||typeof screen.orientation!=="undefined";const pointerCoarse=window.matchMedia&&window.matchMedia("(pointer: coarse)").matches;const deviceMemory=navigator.deviceMemory||null;const hwConcurrency=navigator.hardwareConcurrency||null;const pixelRatio=window.devicePixelRatio||1;const viewport={width:Math.max(window.screen.width,window.screen.height),height:Math.min(window.screen.width,window.screen.height)};return{touch,hasOrientation,pointerCoarse,deviceMemory,hwConcurrency,pixelRatio,viewport}}
async function evaluate(){const results={};const base=androidBaseSignals();results.base=base;results.touchAndPointer=uiCapabilities();const renderer=getWebGLRenderer();results.webglRenderer=renderer;const[canvasHash,audioHash,motionSeen,battery]=await Promise.race([Promise.all([getCanvasFingerprint(),getAudioFingerprint(),captureMotion(600),getBatteryInfo()]),new Promise(resolve=>setTimeout(()=>resolve(["","",!1,null]),TIMEOUT_MS))]).catch(()=>["","",!1,null]);results.canvasHash=canvasHash;results.audioHash=audioHash;results.motionSeen=motionSeen;results.battery=battery;const languages=navigator.languages||[navigator.language||""];const tz=(()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(e){return""}})();results.languages=languages;results.timezone=tz;let score=0;let max=0;const weights={uaAndroid:0.18,platformAndroid:0.12,vendorAndroid:0.06,touch:0.12,pointerCoarse:0.06,orientation:0.04,webglGPU:0.12,canvas:0.05,audio:0.05,motion:0.06,deviceMemory:0.03,languagesTz:0.03};max+=weights.uaAndroid;if(base.uaAndroid)score+=weights.uaAndroid;max+=weights.platformAndroid;if(base.platformAndroid)score+=weights.platformAndroid;max+=weights.vendorAndroid;if(base.vendorAndroid)score+=weights.vendorAndroid;max+=weights.touch;if(results.touchAndPointer.touch)score+=weights.touch;max+=weights.pointerCoarse;if(results.touchAndPointer.pointerCoarse)score+=weights.pointerCoarse;max+=weights.orientation;if(results.touchAndPointer.hasOrientation)score+=weights.orientation;max+=weights.webglGPU;const rendererStr=String(renderer||"");const gpuHints=["adreno","mali","powervr","tegra","arm","qualcomm"];const gpuMatch=gpuHints.some(h=>rendererStr.includes(h));if(gpuMatch)score+=weights.webglGPU;max+=weights.canvas;if(results.canvasHash)score+=weights.canvas;max+=weights.audio;if(results.audioHash)score+=weights.audio;max+=weights.motion;if(results.motionSeen)score+=weights.motion;max+=weights.deviceMemory;if(results.touchAndPointer.deviceMemory&&results.touchAndPointer.deviceMemory>=1)score+=weights.deviceMemory;max+=weights.languagesTz;const plausibleLang=languages.some(l=>/en|es|zh|hi|bn|ar|pt|ru|id|ja|ko/.test(l));if(plausibleLang)score+=weights.languagesTz*0.6;if(tz&&tz.toLowerCase().includes("asia")===!1){}
const normalized=(max>0)?(score/max):0;return{results,score:normalized}}
async function gate(){const ua=(navigator.userAgent||"").toLowerCase();if(!ua.includes("android")&&(ua.includes("iphone")||ua.includes("ipad")||ua.includes("macintosh")||ua.includes("windows nt"))){window.location.replace("/nonsup.html");return}
const evalPromise=evaluate();let evalResult;try{evalResult=await Promise.race([evalPromise,new Promise(resolve=>setTimeout(()=>resolve({results:null,score:0}),TIMEOUT_MS+200))])}catch(e){evalResult={results:null,score:0}}
const pass=evalResult.score>=THRESHOLD;if(!pass){window.location.replace("/nonsup.html")}else{}}
document.addEventListener("DOMContentLoaded",()=>{setTimeout(gate,60)})})()
